name: CI Workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  style:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2

      - name: Install dependencies
        run: composer install  --prefer-dist --no-progress

      - name: Check style
        run: composer test:lint

      - name: Check types
        run: composer test:types

  tests:
    runs-on: ubuntu-22.04
    continue-on-error: true
    strategy:
      matrix:
        operating-system: [ ubuntu-latest ]
        php: ['8.3', '8.4']
        symfony: ['6.4.*', '7.4.*']
        depLevel: ['lowest', 'highest']
    steps:
      - uses: actions/checkout@master

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: flex

      - name: Download dependencies
        env:
          SYMFONY_REQUIRE: ${{ matrix.symfony }}
        uses: ramsey/composer-install@v3
        with:
          dependency-versions: ${{ matrix.depLevel }}

      - name: Run test suite
        run: composer test:feature
